/**
 * C 层新句补写清单（2026-09-20）
 *
 * 背景：审计实测 684 道 practice 题中 90.1% 的答案在本课已原样出现过
 * （A 层纯重复目标句 19.0% + B 层课内原句再现 71.1%），真正需要自己组织的只有 9.9%。
 * 「练」段因此只有一种费脑程度——用户在抄写，不是在检索。
 *
 * 本清单为缺「C 层席位」的课各补 1 道新句题：答案不在本课任何展示文本中出现，
 * 但每个词都在本课（含此前累计）教过——用户拼得出来，只是课内没写过这句。
 *
 * 口径（G1，见 deliverables/product-strategy/prd-grammar-content-quality-absorption-2026-09-20.md）：
 *   A = 答案 == 本课目标句   B = 答案在本课展示池中   C = 新句、词全学过
 *   D = 新句、含未教词（缺陷）
 */
export const C_LAYER_ADDITIONS: Array<{
  number: number;
  promptZh: string;
  tokens: string[];
  distractors: string[];
  answer: string;
}> = [
  { number: 3, promptZh: "同桌问你有什么，你想说：我有一个大杯子。",
    tokens: ["I", "have", "a", "big", "cup."], distractors: ["has"], answer: "I have a big cup." },
  { number: 4, promptZh: "妈妈问你想吃什么，你想说：我想要一个大苹果。",
    tokens: ["I", "want", "a", "big", "apple."], distractors: ["an"], answer: "I want a big apple." },
  { number: 5, promptZh: "同学问你的喜好，你想说：我喜欢咖啡。",
    tokens: ["I", "like", "coffee."], distractors: ["likes"], answer: "I like coffee." },
  { number: 6, promptZh: "看了一眼手表，你想说：现在是九点。",
    tokens: ["It", "is", "nine", "o'clock."], distractors: ["are"], answer: "It is nine o'clock." },
  { number: 7, promptZh: "拍合照前，你想说：他们准备好了。",
    tokens: ["They", "are", "ready."], distractors: ["is"], answer: "They are ready." },
  { number: 11, promptZh: "介绍家里的兄弟，你想说：我有两个哥哥。",
    tokens: ["I", "have", "two", "brothers."], distractors: ["brother"], answer: "I have two brothers." },
  { number: 12, promptZh: "和朋友约周末，你想说：我明天要去公园。",
    tokens: ["I", "will", "go", "to", "the", "park", "tomorrow."], distractors: ["went"], answer: "I will go to the park tomorrow." },
  { number: 17, promptZh: "比个子的时候，你想说：我比你高。",
    tokens: ["I", "am", "taller", "than", "you."], distractors: ["tall"], answer: "I am taller than you." },
  { number: 18, promptZh: "找书的时候，你想说：我的书在桌子上。",
    tokens: ["My", "book", "is", "on", "the", "desk."], distractors: ["in"], answer: "My book is on the desk." },
  { number: 21, promptZh: "说她刚做完的事，你想说：她写完作业了。",
    tokens: ["She", "has", "finished", "her", "homework."], distractors: ["have"], answer: "She has finished her homework." },
  { number: 23, promptZh: "说她弄坏了杯子，你想说：她弄坏了她的杯子。",
    tokens: ["She", "has", "broken", "her", "cup."], distractors: ["have"], answer: "She has broken her cup." },
  { number: 26, promptZh: "带同学看教室，你想说：桌上有一本书。",
    tokens: ["There", "is", "a", "book", "on", "the", "table."], distractors: ["are"], answer: "There is a book on the table." },
  { number: 27, promptZh: "问同学怎么上学，你想说：你怎么去上学？",
    tokens: ["How", "do", "you", "go", "to", "school?"], distractors: ["does"], answer: "How do you go to school?" },
  { number: 28, promptZh: "说你的习惯，你想说：我从来不迟到。",
    tokens: ["I", "am", "never", "late."], distractors: ["always"], answer: "I am never late." },
  { number: 29, promptZh: "说你们的周末安排，你想说：我们要去看电影。",
    tokens: ["We", "are", "going", "to", "watch", "a", "movie."], distractors: ["go"], answer: "We are going to watch a movie." },
  { number: 30, promptZh: "看看教室，你想说：桌上有些书。",
    tokens: ["There", "are", "some", "books", "on", "the", "table."], distractors: ["is"], answer: "There are some books on the table." },
  { number: 31, promptZh: "挑花的时候，你想说：这是最大的一朵花。",
    tokens: ["This", "is", "the", "biggest", "flower."], distractors: ["big"], answer: "This is the biggest flower." },
  { number: 32, promptZh: "教室里有点闷，你想说：请把窗户打开。",
    tokens: ["Please", "open", "the", "window."], distractors: ["opens"], answer: "Please open the window." },
  { number: 40, promptZh: "介绍她读的书，你想说：这些是她读的书。",
    tokens: ["These", "are", "the", "books", "which", "she", "reads."], distractors: ["who"], answer: "These are the books which she reads." },
  { number: 45, promptZh: "说妹妹的爱好，你想说：她喜欢画画。",
    tokens: ["She", "enjoys", "drawing."], distractors: ["draw"], answer: "She enjoys drawing." },
  { number: 48, promptZh: "如果你出门时下雨，会怎样？你想说：如果下雨，我们就待在家里。",
    tokens: ["If", "it", "rains,", "we", "will", "stay", "at", "home."], distractors: ["staying"], answer: "If it rains, we will stay at home." },
  { number: 49, promptZh: "说天冷该做什么，你想说：如果天冷，你应该早点回家。",
    tokens: ["You", "should", "go", "home", "early", "if", "it", "is", "cold."], distractors: ["shouldn't"], answer: "You should go home early if it is cold." },
  { number: 56, promptZh: "填表格的时候，你想说：我的生日在一月。",
    tokens: ["My", "birthday", "is", "in", "January."], distractors: ["on"], answer: "My birthday is in January." },
  { number: 57, promptZh: "看日历约时间，你想说：我们在十月一日见面。",
    tokens: ["We", "meet", "on", "October", "1."], distractors: ["in"], answer: "We meet on October 1." },
  { number: 58, promptZh: "夸同学做事认真，你想说：她看书很认真。",
    tokens: ["She", "reads", "carefully."], distractors: ["careful"], answer: "She reads carefully." },
  { number: 59, promptZh: "夸同学唱歌，你想说：他唱得很好。",
    tokens: ["He", "sings", "very", "well."], distractors: ["good"], answer: "He sings very well." },
  { number: 60, promptZh: "翻旧照片，你想说：公园里有两朵花。",
    tokens: ["There", "were", "two", "flowers", "in", "the", "park."], distractors: ["was"], answer: "There were two flowers in the park." },
  { number: 61, promptZh: "请同学帮忙开门，你想说：你能帮我打开门吗？",
    tokens: ["Could", "you", "help", "me", "open", "the", "door?"], distractors: ["Couldn't"], answer: "Could you help me open the door?" },
  { number: 62, promptZh: "点单时你想说：她想要一杯茶。",
    tokens: ["She", "would", "like", "a", "cup", "of", "tea."], distractors: ["want"], answer: "She would like a cup of tea." },
  { number: 63, promptZh: "请同学把书递过来，你想说：请把那本书给我。",
    tokens: ["Please", "give", "the", "book", "to", "me."], distractors: ["gives"], answer: "Please give the book to me." },
  { number: 64, promptZh: "告诉妈妈你读完了，你想说：我读完了那个故事。",
    tokens: ["I", "finished", "reading", "the", "story."], distractors: ["read"], answer: "I finished reading the story." },
  { number: 65, promptZh: "比个子的时候，你想说：这个男孩和我一样高。",
    tokens: ["This", "boy", "is", "as", "tall", "as", "me."], distractors: ["taller"], answer: "This boy is as tall as me." },
  { number: 66, promptZh: "搬箱子搬不动，你想说：这个箱子太重了搬不动。",
    tokens: ["This", "box", "is", "too", "heavy", "to", "carry."], distractors: ["carrying"], answer: "This box is too heavy to carry." },
  { number: 67, promptZh: "介绍同学的长处，你想说：她擅长唱歌。",
    tokens: ["She", "is", "good", "at", "singing."], distractors: ["sing"], answer: "She is good at singing." },
  { number: 68, promptZh: "说你给妈妈买了什么，你想说：我给妈妈买了一个包。",
    tokens: ["I", "bought", "a", "bag", "for", "my", "mom."], distractors: ["buy"], answer: "I bought a bag for my mom." },
  { number: 69, promptZh: "屋里有点闷，你想说：你介意把门打开吗？",
    tokens: ["Would", "you", "mind", "opening", "the", "door?"], distractors: ["open"], answer: "Would you mind opening the door?" },
  { number: 70, promptZh: "给客人倒喝的，你想说：你想要一些咖啡吗？",
    tokens: ["Would", "you", "like", "some", "coffee?"], distractors: ["any"], answer: "Would you like some coffee?" },
  { number: 71, promptZh: "说这个包你能拎动，你想说：这个包够大，拎得动。",
    tokens: ["This", "bag", "is", "big", "enough", "to", "carry."], distractors: ["heavy"], answer: "This bag is big enough to carry." },
  { number: 72, promptZh: "问同学去图书馆的频率，你想说：你多久去一次图书馆？",
    tokens: ["How", "often", "do", "you", "go", "to", "the", "library?"], distractors: ["does"], answer: "How often do you go to the library?" },
  { number: 73, promptZh: "问同学坐车要多久，你想说：坐公交车要花多久？",
    tokens: ["How", "long", "does", "it", "take", "by", "bus?"], distractors: ["takes"], answer: "How long does it take by bus?" },
  { number: 76, promptZh: "同学问你今天感觉如何，你想说：我现在感觉好多了。",
    tokens: ["I", "feel", "much", "better", "now."], distractors: ["good"], answer: "I feel much better now." },
  { number: 77, promptZh: "说你晚上坚持做的事，你想说：她晚上一直在看书。",
    tokens: ["She", "keeps", "reading", "at", "night."], distractors: ["keep"], answer: "She keeps reading at night." },
  { number: 78, promptZh: "说你的日常，你想说：我每天早上都走路。",
    tokens: ["I", "walk", "every", "morning."], distractors: ["walking"], answer: "I walk every morning." },
  { number: 79, promptZh: "说教室里的座位，你想说：我坐在窗户旁边。",
    tokens: ["I", "sit", "next", "to", "the", "window."], distractors: ["at"], answer: "I sit next to the window." },
  { number: 80, promptZh: "找小猫，你想说：猫在公园前面。",
    tokens: ["The", "cat", "is", "in", "front", "of", "the", "park."], distractors: ["behind"], answer: "The cat is in front of the park." },
  { number: 81, promptZh: "说东西摆放的位置，你想说：猫坐在那些盒子中间。",
    tokens: ["The", "cat", "sits", "between", "the", "boxes."], distractors: ["among"], answer: "The cat sits between the boxes." },
  { number: 82, promptZh: "收拾东西的时候，你想说：我把包放在桌子上了。",
    tokens: ["I", "put", "my", "bag", "on", "the", "table."], distractors: ["putted"], answer: "I put my bag on the table." },
  { number: 83, promptZh: "说你带了东西给他，你想说：我包里有点东西。",
    tokens: ["I", "have", "something", "in", "my", "bag."], distractors: ["anything"], answer: "I have something in my bag." },
  { number: 84, promptZh: "看一眼桌面，你想说：桌子上什么都没有。",
    tokens: ["There", "is", "nothing", "on", "the", "desk."], distractors: ["anything"], answer: "There is nothing on the desk." },
  { number: 85, promptZh: "捡到一把伞，你想问：这把伞是谁的？",
    tokens: ["Whose", "umbrella", "is", "this?"], distractors: ["Who"], answer: "Whose umbrella is this?" },
  { number: 86, promptZh: "指着门边的那个包，你想说：那个包在门旁边。",
    tokens: ["The", "bag", "is", "next", "to", "the", "door."], distractors: ["in"], answer: "The bag is next to the door." },
  { number: 87, promptZh: "看窗外的好天气，你想说：今天天晴。",
    tokens: ["It's", "sunny", "today."], distractors: ["Its"], answer: "It's sunny today." },
  { number: 88, promptZh: "摸了摸手，你想说：今天不冷。",
    tokens: ["It's", "not", "cold", "today."], distractors: ["wind"], answer: "It's not cold today." },
  { number: 89, promptZh: "看到同学的大包，你想说：多大的包啊！",
    tokens: ["What", "a", "big", "bag!"], distractors: ["big a"], answer: "What a big bag!" },
  { number: 90, promptZh: "说你的作息，你想说：我吃完晚饭后玩游戏。",
    tokens: ["After", "I", "eat", "dinner,", "I", "play", "games."], distractors: ["before"], answer: "After I eat dinner, I play games." },
  { number: 91, promptZh: "说你的睡前习惯，你想说：我睡前喝水。",
    tokens: ["Before", "I", "sleep,", "I", "drink", "water."], distractors: ["after"], answer: "Before I sleep, I drink water." },
  { number: 92, promptZh: "说你的习惯，你想说：下雨的时候我在家看书。",
    tokens: ["When", "it", "is", "rainy,", "I", "read."], distractors: ["rain"], answer: "When it is rainy, I read." },
  { number: 93, promptZh: "回忆从前，你想说：我从前天天在这儿跑步。",
    tokens: ["I", "used", "to", "run", "here", "every", "day."], distractors: ["use"], answer: "I used to run here every day." },
  { number: 95, promptZh: "说昨晚八点在做什么，你想说：昨晚八点我正在睡觉。",
    tokens: ["I", "was", "sleeping", "at", "eight", "last", "night."], distractors: ["were"], answer: "I was sleeping at eight last night." },
  { number: 96, promptZh: "回忆昨天那个时间，你想说：当时八点正下着雨。",
    tokens: ["It", "was", "raining", "at", "eight."], distractors: ["were"], answer: "It was raining at eight." },
  { number: 97, promptZh: "说昨天被打断的事，你想说：你打电话的时候我正在画画。",
    tokens: ["When", "you", "called,", "I", "was", "drawing."], distractors: ["call"], answer: "When you called, I was drawing." },
  { number: 98, promptZh: "说两件事同时发生，你想说：我看书的时候她在做饭。",
    tokens: ["While", "I", "was", "reading,", "she", "was", "cooking."], distractors: ["cooked"], answer: "While I was reading, she was cooking." },
  { number: 99, promptZh: "说被打断的那一刻，你想说：电话响的时候我正在做饭。",
    tokens: ["I", "was", "cooking", "when", "the", "phone", "rang."], distractors: ["ring"], answer: "I was cooking when the phone rang." },
  { number: 102, promptZh: "回忆那个时间，你想说：八点的时候我正在睡觉。",
    tokens: ["I", "was", "sleeping", "at", "eight."], distractors: ["were"], answer: "I was sleeping at eight." },
  { number: 103, promptZh: "说家里的规矩，你想说：我爸爸让我每天运动。",
    tokens: ["My", "dad", "makes", "me", "play", "sports", "every", "day."], distractors: ["make"], answer: "My dad makes me play sports every day." },
  { number: 104, promptZh: "说昨天发生的事，你想说：她昨天让我打扫房间。",
    tokens: ["She", "made", "me", "clean", "my", "room", "yesterday."], distractors: ["make"], answer: "She made me clean my room yesterday." },
  { number: 105, promptZh: "说妈妈的规定，你想说：她不让我出门。",
    tokens: ["She", "doesn't", "let", "me", "go", "out."], distractors: ["lets"], answer: "She doesn't let me go out." },
  { number: 107, promptZh: "说老师让你做事，你想说：老师让我早点回家。",
    tokens: ["The", "teacher", "had", "me", "go", "home", "early."], distractors: ["have"], answer: "The teacher had me go home early." },
  { number: 108, promptZh: "说你怎么说动他，你想说：我说动他来帮我。",
    tokens: ["I", "got", "him", "to", "help", "me."], distractors: ["get"], answer: "I got him to help me." },
  { number: 109, promptZh: "说昨天等到很晚，你想说：她一直等到雨停。",
    tokens: ["She", "waited", "until", "the", "rain", "stopped."], distractors: ["stops"], answer: "She waited until the rain stopped." },
  { number: 110, promptZh: "说妈妈的要求，你想说：我妈妈让我每天学习。",
    tokens: ["My", "mom", "makes", "me", "study", "every", "day."], distractors: ["make"], answer: "My mom makes me study every day." },
  { number: 111, promptZh: "说她家人的生日，你想说：我奶奶的生日在五月。",
    tokens: ["My", "grandma's", "birthday", "is", "in", "May."], distractors: ["grandma"], answer: "My grandma's birthday is in May." },
  { number: 112, promptZh: "说这个包是谁的，你想说：这个包是我哥哥的。",
    tokens: ["This", "bag", "is", "my", "brother's."], distractors: ["mine"], answer: "This bag is my brother's." },
  { number: 113, promptZh: "说你的感受，你想说：我对这本书感到无聊。",
    tokens: ["I", "am", "bored", "with", "this", "book."], distractors: ["boring"], answer: "I am bored with this book." },
  { number: 114, promptZh: "打开冰箱看看，你想说：冰箱里还有几个苹果。",
    tokens: ["There", "are", "a", "few", "apples", "in", "the", "fridge."], distractors: ["little"], answer: "There are a few apples in the fridge." },
  { number: 115, promptZh: "介绍你有的东西，你想说：我有一个新书包。",
    tokens: ["I", "have", "got", "a", "new", "bag."], distractors: ["has"], answer: "I have got a new bag." },
  { number: 116, promptZh: "介绍她的新自行车，你想说：她有一辆新自行车。",
    tokens: ["She", "has", "got", "a", "new", "bike."], distractors: ["have"], answer: "She has got a new bike." },
  { number: 117, promptZh: "说你有新书包，你想说：我有一个新书包。",
    tokens: ["I", "have", "got", "a", "new", "bag."], distractors: ["has"], answer: "I have got a new bag." },
  { number: 118, promptZh: "介绍她的新自行车，你想说：她有一辆新自行车。",
    tokens: ["She", "has", "got", "a", "new", "bike."], distractors: ["have"], answer: "She has got a new bike." },
  { number: 119, promptZh: "适应了新住处，你想说：我习惯了这个房子。",
    tokens: ["I", "am", "used", "to", "the", "house."], distractors: ["use"], answer: "I am used to the house." },
  { number: 120, promptZh: "说你的习惯，你想说：我习惯了走路去上学。",
    tokens: ["I", "am", "used", "to", "walking", "to", "school."], distractors: ["walk"], answer: "I am used to walking to school." },
  { number: 121, promptZh: "说正在慢慢适应，你想说：我正在慢慢习惯这个学校。",
    tokens: ["I", "am", "getting", "used", "to", "this", "school."], distractors: ["get"], answer: "I am getting used to this school." },
  { number: 122, promptZh: "回忆她的从前，你想说：她从前常走着去上学。",
    tokens: ["She", "used", "to", "walk", "to", "school."], distractors: ["use"], answer: "She used to walk to school." },
  { number: 123, promptZh: "说还没适应的事，你想说：我还没习惯这个新学校。",
    tokens: ["I", "am", "not", "used", "to", "this", "new", "school."], distractors: ["use"], answer: "I am not used to this new school." },
  { number: 124, promptZh: "说她还没适应，你想说：她还没习惯这里的冷。",
    tokens: ["She", "is", "not", "used", "to", "the", "cold."], distractors: ["use"], answer: "She is not used to the cold." },
  { number: 125, promptZh: "看同学的画，你想说：这幅画看起来很好。",
    tokens: ["This", "drawing", "looks", "good."], distractors: ["look"], answer: "This drawing looks good." },
  { number: 126, promptZh: "看同学的脸，你想说：他今天看起来很开心。",
    tokens: ["He", "looks", "happy", "today."], distractors: ["look"], answer: "He looks happy today." },
  { number: 127, promptZh: "看教室的新桌子，你想说：这张桌子看起来是新的。",
    tokens: ["This", "desk", "looks", "new."], distractors: ["look"], answer: "This desk looks new." },
  { number: 128, promptZh: "听了同学的提议，你想说：那个听起来很棒。",
    tokens: ["That", "sounds", "great."], distractors: ["sound"], answer: "That sounds great." },
  { number: 129, promptZh: "闻到厨房的汤，你想说：这个汤闻起来很好。",
    tokens: ["The", "soup", "smells", "good."], distractors: ["smell"], answer: "The soup smells good." },
  { number: 130, promptZh: "尝了一口点心，你想说：这个点心尝起来不错。",
    tokens: ["The", "cake", "tastes", "nice."], distractors: ["taste"], answer: "The cake tastes nice." },
  { number: 131, promptZh: "摸了一下点心，你想说：这个点心的摸着是凉的。",
    tokens: ["The", "cake", "feels", "cold."], distractors: ["feel"], answer: "The cake feels cold." },
  { number: 132, promptZh: "问同学汤的味道，你想说：这个汤尝起来好吗？",
    tokens: ["Does", "the", "soup", "taste", "good?"], distractors: ["tastes"], answer: "Does the soup taste good?" },
  { number: 133, promptZh: "尝了妈妈做的汤，你想说：这个汤尝起来很好。",
    tokens: ["The", "soup", "tastes", "good."], distractors: ["taste"], answer: "The soup tastes good." },
  { number: 135, promptZh: "说妹妹的期待，你想说：她盼着周末。",
    tokens: ["She", "looks", "forward", "to", "the", "weekend."], distractors: ["look"], answer: "She looks forward to the weekend." },
  { number: 136, promptZh: "说你的期待，你想说：我盼着见到她。",
    tokens: ["I", "am", "looking", "forward", "to", "seeing", "her."], distractors: ["see"], answer: "I am looking forward to seeing her." },
  { number: 138, promptZh: "说她的习惯，你想说：她习惯了早起。",
    tokens: ["She", "is", "used", "to", "getting", "up", "early."], distractors: ["get"], answer: "She is used to getting up early." },
  { number: 139, promptZh: "说虽然累还是要做，你想说：虽然我很累，我还是要去。",
    tokens: ["Although", "I", "am", "tired,", "I", "will", "go."], distractors: ["but"], answer: "Although I am tired, I will go." },
  { number: 140, promptZh: "说虽然冷还是要出去，你想说：虽然天冷，我们还是要出去。",
    tokens: ["Although", "it", "is", "cold,", "we", "will", "go", "out."], distractors: ["but"], answer: "Although it is cold, we will go out." },
  { number: 141, promptZh: "说虽然忙还是开心，你想说：虽然我很忙，我依然很开心。",
    tokens: ["Although", "I", "am", "busy,", "I", "am", "happy."], distractors: ["but"], answer: "Although I am busy, I am happy." },
  { number: 142, promptZh: "说吃完就打电话，你想说：我一吃完就给你打电话。",
    tokens: ["As", "soon", "as", "I", "finish,", "I", "will", "call", "you."], distractors: ["calling"], answer: "As soon as I finish, I will call you." },
  { number: 143, promptZh: "说吃完就去，你想说：我一吃完就走。",
    tokens: ["As", "soon", "as", "I", "finish,", "I", "will", "go."], distractors: ["when"], answer: "As soon as I finish, I will go." },
  { number: 144, promptZh: "说洗完手就吃，你想说：我一洗完手就吃饭。",
    tokens: ["As", "soon", "as", "I", "wash", "my", "hands,", "I", "will", "eat."], distractors: ["before"], answer: "As soon as I wash my hands, I will eat." },
  { number: 146, promptZh: "说你也一样但带否定，你想说：我也不喜欢茶。",
    tokens: ["I", "don't", "like", "tea", "either."], distractors: ["too"], answer: "I don't like tea either." },
  { number: 149, promptZh: "说这些书没有一本是好的，你想说：这些书没有一本是好的。",
    tokens: ["Neither", "of", "the", "books", "is", "good."], distractors: ["Both"], answer: "Neither of the books is good." },
  { number: 150, promptZh: "说两本书都好，你想说：这两本书都很好。",
    tokens: ["Both", "of", "the", "books", "are", "good."], distractors: ["Neither"], answer: "Both of the books are good." },
  { number: 153, promptZh: "说作业还没写完，你想说：我还没写完作业。",
    tokens: ["I", "haven't", "finished", "my", "homework", "yet."], distractors: ["already"], answer: "I haven't finished my homework yet." },
  { number: 157, promptZh: "说这些东西一件都不是她的，你想说：这些东西一件都不是她的。",
    tokens: ["None", "of", "them", "are", "hers."], distractors: ["Nothing"], answer: "None of them are hers." }
];
